[package]
name = "EmpireReportSettings"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.134"
serde = { version = "1.0.217", features = ["derive"] }
ssql = { version = "0.2.0", features = ["chrono", "serde"] }
sendgrid = { version = "0.23.0" }
